spring:
  application:
    name: ecom
  datasource:
    url: ${URL}
    username: ${NAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration : 900 #2hours
    refreshTokenExpiration : 604800 #7days
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:3000