spring:
  application:
    name: ecom
  datasource:
    url: 
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration : 900 #15min
    refreshTokenExpiration : 604800 #7days
